Repository sayak2k1maruti/competetivePogramming, pull requests merged in 2021-10, with the labels that each got.

#5 solved this issue #1
  CP/CodeChef/DAREA/filename.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#2 DAREA solved
  CP/CodeChef/DAREA/Cronus1007.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#13 Solved issue #11
  CP/LeetCode/Longest Substring Without Repeating Characters/sayak01.cpp
Labels: hacktoberfest-accepted

#14 Solved issue #10
  CP/CodeChef/DAREA/sayak01.cpp
  CP/CodeChef/SHROUTE/sayak01.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#12 Added solution for issue number #10
  CP/CodeChef/SHROUTE/SugatoBagchi.cpp
Labels: hacktoberfest-accepted

#15 Solution for Partition to K Equal Sum Subsets #7
  CP/LeetCode/Partition to K Equal Sum Subsets/sayak01.cpp
Labels: hacktoberfest-accepted

#9 Partition to K Equal Sum Subsets solved
  CP/LeetCode/Partition to K Equal Sum Subsets/Cronus1007.cpp
Labels: hacktoberfest-accepted

#8 write a commit msg here
  CP/CodeChef/DAREA/iamssss.cpp
Labels: hacktoberfest-accepted

#16 Edited ./CP/README.md ISSUE #3
  CP/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#19 please merge
  CP/CodeChef/SHROUTE/sroute.cpp
  CP/LeetCode/lcswrc.cpp
  CP/Longest Substring Without Repeating Characters.cpp
  CP/Longest-Substring-Without-Repeating-Characters.cpp
Labels: Hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#25 done
  C++/knapsnak_dp_memorise_arr/knapsnak_dp_memorise_arr.cpp
Labels: hacktoberfest-accepted

#38 Count Complete Tree Nodes
  CP/LeetCode/Count Complete Tree Nodes/README.md
  CP/LeetCode/Count Complete Tree Nodes/Supratim2000.cpp
Labels: Hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#46 Create Harshgupta5901.py
  CP/LeetCode/Count Complete Tree Nodes/Harshgupta5901.py
Labels: Hacktoberfest, hacktoberfest2021, hacktoberfest-accepted
