Repository sayak2k1maruti/competetivePogramming, pull requests merged in 2022-10, with the labels that each got.

#84 Regular Expression Matching
  CP/LeetCode/Regular Expression Matching/krishnasharma1386.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#92 Create sayak01.cpp issue #78
  CP/LeetCode/Longest Palindromic Substring/sayak01.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#91 solved problem longest palindromic substring
  CP/LeetCode/Longest Pallindromic Substring/I-am-SS.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#90 solved longest palindromic substring
  CP/LeetCode/Longest Pallindromic Substring/username.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#89 solved longest palindromic substring
  CP/LeetCode/Longest Palindromic Substring/iamssss.cpp
  CP/LeetCode/Longest Pallindromic Substring/iamssss.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#87 Added roushan-rks.cpp file (5. Longest Palindromic Substring) solution
  CP/LeetCode/Longest Palindromic Substring/roushan-rks.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#86 Create C++_ solution.cpp
  CP/LeetCode/Longest Palindromic Substring/C++_ solution.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#88 Solved problem of Longest palindromic Substring
  CP/LeetCode/Longest Palindromic Substring/saptarshisarkar20.cpp
  CP/LeetCode/Regular Expression Matching/saptarshisarkar20.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#83 Created Regular Expression Matching in Python Language
  CP/LeetCode/Regular Expression Matching/ShinchanTheMaster.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#81 Added Added Longest Palindromic Substring in C++
  CP/LeetCode/Longest Palindromic Substring/lucy2512.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#77 Add counting sort algorithm in C++ language
  C++/CountingSort.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#75 solved Partition to K Equal Sum Subsets
  CP/LeetCode/Partition to K Equal Sum Subsets/Partition to K Equal Sum Subsets
Labels: Hacktoberfest, hacktoberfest-accepted

#98 solved reg expression matching using python
  CP/LeetCode/Regular Expression Matching/I-am-SS.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#97 solved the problem of regular expressions matching
  CP/LeetCode/Regular Expression Matching/what-should-be-my-username.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#95 solved regular expression matching
  CP/LeetCode/Regular Expression Matching/iamssss.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#94 solved problem of regular expression matching
  CP/LeetCode/Regular Expression Matching/sarkar20.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#100 solved problem of logest palindromic substring
  CP/LeetCode/Longest Palindromic Substring/saptarshisarkar20.java
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#99 solved problem using python programming language
  CP/LeetCode/Longest Substring Without Repeating Characters/saptarshisarkar20.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#101 Added Regular Expression Matching , Issue #76
  CP/LeetCode/Regular Expression Matching/sayak01.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#102 Longest Palindromic Substring C++
  C++/LongestPalindromicSubstring.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#104 Added Container With Most Water ISSUE #103
  CP/LeetCode/Container With Most Water/sayak01.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#105 Add files via upload
  CP/LeetCode/429-n-ary-tree-level-order-traversal/429-n-ary-tree-level-order-traversal.cpp
  CP/LeetCode/429-n-ary-tree-level-order-traversal/NOTES.md
  CP/LeetCode/429-n-ary-tree-level-order-traversal/README.md
  CP/LeetCode/94-binary-tree-inorder-traversal/94-binary-tree-inorder-traversal.cpp
  CP/LeetCode/94-binary-tree-inorder-traversal/NOTES.md
  CP/LeetCode/94-binary-tree-inorder-traversal/README.md
  CP/LeetCode/987-vertical-order-traversal-of-a-binary-tree/987-vertical-order-traversal-of-a-binary-tree.cpp
  CP/LeetCode/987-vertical-order-traversal-of-a-binary-tree/NOTES.md
  CP/LeetCode/987-vertical-order-traversal-of-a-binary-tree/README.md
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#107 Add files via upload
  118-pascals-triangle/118-pascals-triangle.cpp
  118-pascals-triangle/NOTES.md
  118-pascals-triangle/README.md
  119-pascals-triangle-ii/NOTES.md
  119-pascals-triangle-ii/README.md
  121-best-time-to-buy-and-sell-stock/121-best-time-to-buy-and-sell-stock.cpp
  121-best-time-to-buy-and-sell-stock/NOTES.md
  121-best-time-to-buy-and-sell-stock/README.md
  122-best-time-to-buy-and-sell-stock-ii/122-best-time-to-buy-and-sell-stock-ii.cpp
  122-best-time-to-buy-and-sell-stock-ii/NOTES.md
  122-best-time-to-buy-and-sell-stock-ii/README.md
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#106 Added number systems conversions folder
  C++/number-systems/binaryToDecimal.cpp
  C++/number-systems/decimalToBinary.cpp
  C++/number-systems/decimalToHexadecimal.cpp
  C++/number-systems/decimalToOctal.cpp
  C++/number-systems/hexaDecimalToDecimal.cpp
  C++/number-systems/octalToDecimal.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#109 Added Integer to Roman ISSUE #108
  CP/LeetCode/Integer To Roman/sayak01.cpp
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#117 Added Leetcode Solution
  CP/LeetCode/Letter Combination of a Phone Number/Prakhar9450.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#140 YuvrajRakheja.py
  CP/LeetCode/4Sum/YuvrajRakheja.py
  CP/LeetCode/Container With Most Water/YuvrajRakheja.py
Labels: hacktoberfest-accepted

#137 solve this problem of roman to int
  CP/LeetCode/Integer To Roman/sneha3215.cpp
Labels: hacktoberfest-accepted

#126 count_complete_tree_nodes
  CP/LeetCode/Count Complete Tree Nodes/count_complete_tree_nodes.cpp
Labels: hacktoberfest-accepted

#123 Added code for 4 sum
  CP/LeetCode/4Sum/blaze116.cpp
Labels: hacktoberfest-accepted

#142 My solution using c plus plus
  CP/LeetCode/Integer To Roman/usingVector.cpp
Labels: hacktoberfest-accepted

#144 Longest Substring Without Repeating Characters
  C++/Longest Substring Without Repeating Characters
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#146 Create Rat_in_A_Maze.py
  Learning DSA with Python/Rat_in_A_Maze.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#147 Create 4sumPython.py
  CP/LeetCode/4sumPython.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#148 Added bubblesort
  Learning DSA with Python/bubblesort.py
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#132 solve this using java
  CP/LeetCode/4Sum/I-am-SS.java
Labels: hacktoberfest-accepted
